DROP DATABASE IF EXISTS `student_mental_health`;
CREATE DATABASE `student_mental_health`;
USE `student_mental_health`;

CREATE TABLE mental_health_data
( 
	`index` INT,
	inter_dom VARCHAR(30),
	region VARCHAR(30),
    gender VARCHAR(10),
    academic VARCHAR(15),
    age INT,
    age_cate INT,
	stay INT,
	stay_cate VARCHAR(15),
	japanese INT,
	japanese_cate VARCHAR(20),
	english	INT,
    english_cate VARCHAR(20),
	intimate VARCHAR(10),
	religion VARCHAR(10),
	suicide VARCHAR(10),
	dep VARCHAR(10),
	deptype VARCHAR(10),
	todep INT,
	depsev VARCHAR(10),
	tosc INT,
	apd INT,
	ahome INT,
    aph INT,
	afear INT,
	acs INT,
	aguilt INT,
    amiscell INT,
    toas INT,
    partner INT,
	friends INT,
	parents	INT,
    relative INT,
	profess INT,
	phone INT,
	doctor INT,
	reli INT,
    alone INT,
	others INT,
	internet INT,
	partner_bi VARCHAR(5),
	friends_bi VARCHAR(5),
	parents_bi VARCHAR(5),
	relative_bi VARCHAR(5),
	professional_bi VARCHAR(5),
    phone_bi VARCHAR(5),
	doctor_bi VARCHAR(5),
	religion_bi VARCHAR(5),
    alone_bi VARCHAR(5),
	others_bi VARCHAR(5),
	internet_bi VARCHAR(5)
)
